--usuario
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555');

